name: jngridtest
favicon: null
layout_spectrum: 0.00132
typography_spectrum: 0.88522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#605d5c'
    - '#2695d1'
    - '#cbd5e0'
    - '#aaa9a9'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
