name: jngridtest
favicon: null
layout_spectrum: 0.7238584256265312
typography_spectrum: 0.5846428519580513
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#605d5c'
    - '#ffffff'
    - '#000000'
    - '#ff0000'
    - '#00ffff'
  brandStrength: 0.75
  lightness: 0.6789380153641105
  saturation: 0.12091672932729125
  rhythmicContrast: 0.8924783561378717
purpose: []
